In [1]:
!python -V

Python 3.12.1


In [2]:
import numpy as np

In [3]:
u = np.array([2, 7, 5, 6])

In [4]:
v = np.array([3, 4, 8, 6])


In [5]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [6]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [7]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [9]:
u * v

array([ 6, 28, 40, 36])

In [10]:
I = np.eye(3)